import { Abel, Lato } from "next/font/google";

const abel = Abel({
  weight: "400",
  variable: "--font-abel",
  display: "swap",
  subsets: ["latin"],
});

const lato = Lato({
  weight: "400",
  variable: "--font-lato",
  display: "swap",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={`${abel.variable} ${lato.variable}`} lang="en">
      {children}
    </html>
  );
}
